name = "books-test"
main = "src/main.ts"
compatibility_date = "2024-11-24"
pages_build_output_dir="dist/test-task/browser"

kv_namespaces = [
  { binding = "BOOKS_KV", id = "7cc55d9a2e1340eebbcf5df5ba3183b8" }
]
