name = "books-test"
compatibility_date = "2024-11-24"
pages_build_output_dir="dist/test-task/browser"

[vars]
NODE_VERSION="20.x"

kv_namespaces = [
  { binding = "BOOKS_KV", id = "fe860b63261f4b1f84307b099ec836d0" }
]


